        <a href="../">HOME</a>
        <a href="../#maps">WYBIERZ MAPĘ</a>
        <a href="">MIRAGE</a>
        <a href="">NUKE</a>
        <a href="../Anubis/">ANUBIS</a>
        <a href="">ANCIENT</a>
        <a href="">DUST2</a>
        <a href="">VERTIGO</a>
        <a href="">INFERNO</a>
        <a href="">OVERPASS</a>
        <a href="">INSTAGRAM</a>
        <a href="">YOUTUBE</a>
        <a href="">TIKTOK</a>